# Generated by Django 4.1.3 on 2022-11-22 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('joincode', models.CharField(default='', max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_courses', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='stud_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
