# Generated by Django 4.1.3 on 2022-11-22 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('link', models.URLField(default='')),
                ('file_name', models.CharField(default='problem_statement', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='assignments')),
                ('statement', models.CharField(default='', max_length=300)),
                ('maxmarks', models.IntegerField(default=100)),
                ('deadline', models.DateTimeField()),
                ('weightage', models.IntegerField(default=0)),
                ('feedfile', models.FileField(blank=True, upload_to='feedback')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='submissions')),
                ('file_name', models.CharField(default='submission', max_length=100)),
                ('feedback', models.CharField(default='Your Feedback Appears Here', max_length=500)),
                ('corrected', models.CharField(default='NO', max_length=10)),
                ('grade', models.IntegerField(default=-1)),
                ('sub_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
