# Generated by Django 4.1.3 on 2022-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_filesubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='feedfile',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='extensions',
            field=models.CharField(default='', max_length=128),
        ),
    ]
