# Generated by Django 4.1.3 on 2022-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_assignment_feedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_name',
            field=models.CharField(default='problem_statement', max_length=100),
        ),
    ]
