# Generated by Django 4.1.3 on 2022-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='extensions',
            field=models.PositiveSmallIntegerField(choices=[(1, '.zip'), (2, '.tar'), (3, '.cpp'), (4, '.tar.gz'), (5, '.py'), (6, '.c')]),
        ),
    ]
