# Generated by Django 4.1.3 on 2022-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='extensions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
