# Generated by Django 4.1.3 on 2022-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_assignment_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='text_file',
            field=models.FileField(blank=True, upload_to='submissions'),
        ),
    ]
